default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user_1
  password: test123
  host: localhost
  database: rent_a_bike

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user_1
  password: test123
  host: localhost
  database: rent_a_bike

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: user_1
  host: localhost
  database: rent_a_bike
